python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Aguascalientes/31/Aguascalientes_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Baja_California/31/Baja_California_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Baja_California_Sur/31/Baja_California_Sur_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Campeche/31/Campeche_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Chiapas/31/Chiapas_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Chihuahua/31/Chihuahua_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Coahuila_de_Zaragoza/31/Coahuila_de_Zaragoza_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Colima/31/Colima_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Distrito_Federal/31/Distrito_Federal_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Durango/31/Durango_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Guanajuato/31/Guanajuato_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Guerrero/31/Guerrero_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Hidalgo/31/Hidalgo_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Jalisco/31/Jalisco_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Mexico/31/Mexico_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Michoacan_de_Ocampo/31/Michoacan_de_Ocampo_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Morelos/31/Morelos_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Nayarit/31/Nayarit_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Nuevo_Leon/31/Nuevo_Leon_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Oaxaca/31/Oaxaca_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Puebla/31/Puebla_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Queretaro/31/Queretaro_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Quintana_Roo/31/Quintana_Roo_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/San_Luis_Potosi/31/San_Luis_Potosi_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Sinaloa/31/Sinaloa_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Sonora/31/Sonora_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Tabasco/31/Tabasco_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Tamaulipas/31/Tamaulipas_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Tlaxcala/31/Tlaxcala_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Veracruz_de_Ignacio_de_la_Llave/31/Veracruz_de_Ignacio_de_la_Llave_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Yucatan/31/Yucatan_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/Zacatecas/31/Zacatecas_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json
python read_by_block_schema.py /Volumes/MADMEX/tasks/2018_tasks/mapabase_2018/sentinel2/2018/madmex_sentinel_2018_31.tif /Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json



#/Users/rmartinez/Desktop/cobertura_json/schemas/schema_cobertura31.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_pie.json /Users/rmartinez/Desktop/cobertura_json/templetes/templete_cobertura31_bar.json